

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        {/* <div className="absolute inset-0 bg-my bg-fixed bg-cover bg-center opacity-20 z-0"></div> */}
        <div className="fixed inset-0 bg-my bg-cover bg-center opacity-30 z-0 pointer-events-none"></div>
        
        <div className="relative z-10 snap-y snap-mandatory h-screen overflow-y-scroll ">
          <Navbar/>
          {children}
          <Footer/>
        </div>
        
      </body>
      
    </html>
  );
}
